---
# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: magistrala
description: Magistrala IoT Platform
icon: https://avatars1.githubusercontent.com/u/13207490
type: application
version: "0.15.2"
appVersion: "0.15.1"
home: https://abstractmachines.fr/magistrala.html
sources:
  - https://hub.docker.com/u/magistrala
maintainers:
  - name: drasko
    email: drasko.draskovic@abstractmachines.fr
  - name: dusan
    email: dusan.borovcanin@abstractmachines.fr

dependencies:
  - name: Supermq
    version: "0.16.5"
    repository: "https://absmach.github.io/supermq-devops/"
    alias: supermq
    condition: supermq.enabled

  - name: postgresql
    version: "15.2.10"
    repository: "@bitnami"
    alias: postgresqlbootstrap
    condition: postgresqlbootstrap.enabled

  - name: postgresql
    version: "15.2.10"
    repository: "@bitnami"
    alias: postgresqlreader
    condition: postgresqlreader.enabled

  - name: postgresql
    version: "15.2.10"
    repository: "@bitnami"
    alias: postgresqlwriter
    condition: postgresqlwriter.enabled

  - name: postgresql
    version: "15.2.10"
    repository: "@bitnami"
    alias: timescaledb
    condition: timescaledb.enabled

  - name: postgresql
    version: "15.2.10"
    repository: "@bitnami"
    alias: postgresqlre
    condition: postgresqlre.enabled
